# Generated by Django 2.1.2 on 2018-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_auto_20181108_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentratio',
            name='current_ratio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
