# Generated by Django 2.1.2 on 2018-11-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0004_auto_20181109_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentratio',
            name='current_assets',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currentratio',
            name='current_liabilities',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
