# Generated by Django 2.1.2 on 2018-12-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0007_auto_20181128_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashratio',
            name='cash_ratio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currentratio',
            name='current_ratio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quickratio',
            name='quick_ratio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnonassets',
            name='return_on_assets',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnonequity',
            name='return_on_equity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnonsales',
            name='return_on_sales',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
