# Generated by Django 2.1.2 on 2019-01-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0008_auto_20181211_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_ratio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('year', models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')], default='2018', max_length=64)),
                ('total_liabilities', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_assets', models.DecimalField(decimal_places=3, max_digits=10)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.Company')),
            ],
        ),
        migrations.CreateModel(
            name='DebtToEquityRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_to_equity_ratio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('year', models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')], default='2018', max_length=64)),
                ('total_liabilities', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_equity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.Company')),
            ],
        ),
        migrations.CreateModel(
            name='EquityRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_ratio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('year', models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018')], default='2018', max_length=64)),
                ('total_equity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_assets', models.DecimalField(decimal_places=3, max_digits=10)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.Company')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='equityratio',
            unique_together={('company_name', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='debttoequityratio',
            unique_together={('company_name', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='debtratio',
            unique_together={('company_name', 'year')},
        ),
    ]
